permissions:
  contents: write

name: Generate Landing Pages

on:
  push:
    paths:
      - 'data/FI_DATABASE.csv'
      - 'src/**'
      - 'templates/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your code
      - uses: actions/checkout@v3

      # 2) Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install jinja2 python-dateutil

      # 4) Generate the landing pages
      - name: Generate landing pages
        run: python src/generate_landing_page.py

      # 5) Copy CNAME into output/ (if you use a custom domain)
      - name: Copy CNAME to output/
        run: |
          if [ -f CNAME ]; then cp CNAME output/CNAME; fi

      # 6) Disable Jekyll (so _ underscores etc. aren’t filtered)
      - name: Disable Jekyll
        run: touch output/.nojekyll

      # 7) Deploy output/ to the gh-pages branch
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output

