name: Update Sitemap

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout the gh-pages branch with full history
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      # 2) Generate sitemap.xml using Cicirello’s action
      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          site_root: '.'                                    # look at the root of gh-pages
          base_url: https://formazione-insegnamento.eu      # your mirror URL

      # 3) Commit & push only sitemap.xml back to gh-pages
      - name: Commit sitemap.xml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sitemap.xml
          git diff --quiet --cached || git commit -m "chore: update sitemap.xml"
          git push origin gh-pages
