name: Update Sitemap

on:
  push:
    branches: [gh-pages]   # fires whenever gh-pages is pushed

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Generate sitemap.xml
        uses: cicirello/generate-sitemap@v1   # official action for sitemaps :contentReference[oaicite:0]{index=0}
      - name: Commit sitemap.xml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sitemap.xml
          git diff --quiet --cached || git commit -m "chore: update sitemap.xml"
          git push origin gh-pages
