name: Update Sitemap

# 1️ Trigger whenever gh-pages is updated:
on:
  push:
    branches: [gh-pages]

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      # 2️ Check out the full gh-pages branch (including history)
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0        # ← required for correct <lastmod> dates

      # 3️ Run the cicirello sitemap generator over the checked-out HTML
      - name: Generate sitemap.xml
        uses: cicirello/generate-sitemap@v2
        with:
          base-url: 'https://formazione-insegnamento.eu'
          # (optionally) include-files: '**/*.html'

      # 4️ Commit & push only the updated sitemap.xml
      - name: Commit sitemap.xml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sitemap.xml
          git diff --quiet --cached || git commit -m "chore: update sitemap.xml"
          git push origin gh-pages
