name: Generate Sitemap

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Generate sitemap.xml
        run: python3 ci/generate_sitemap.py

      - name: Commit sitemap.xml
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add sitemap.xml
          git commit -m 'Auto-generate sitemap.xml' || echo "No changes"
          git push
