name: Generate Sitemap

on:
  push:
    branches: [main, ci/landing-pages]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: List files for debugging
        run: ls -R
    
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Generate sitemap.xml
        run: python3 ci/landing-pages/src/generate_sitemap.py

      - name: Move sitemap.xml to output
        run: mv sitemap.xml output/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
