name: Update Sitemap

on:
  push:
    branches: [gh-pages]

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate sitemap.xml
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://formazione-insegnamento.eu/

      - name: Commit sitemap.xml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sitemap.xml
          git diff --quiet --cached || git commit -m "chore: update sitemap.xml"
          git push origin gh-pages
